export const types = Object.freeze({
    // Sync
    CARD_MANAGER_ADD_POPUP_CARD: 'CARD_MANAGER_ADD_POPUP_CARD',
    CARD_MANAGER_CLOSE_POPUP_CARD: 'CARD_MANAGER_CLOSE_POPUP_CARD',
    CARD_MANAGER_EDIT_POPUP_CARD: 'CARD_MANAGER_EDIT_POPUP_CARD',
    CARD_MANAGER_FILL_CARDS: 'CARD_MANAGER_FILL_CARDS',
    CARD_MANAGER_START_FETCHING: 'CARD_MANAGER_START_FETCHING',
    CARD_MANAGER_STOP_FETCHING: 'CARD_MANAGER_STOP_FETCHING',
    CARD_MANAGER_SET_FETCHING_ERROR: 'CARD_MANAGER_SET_FETCHING_ERROR',
    // Async
    CARD_MANAGER_FETCH_CARDS_ASYNC: 'CARD_MANAGER_FETCH_CARDS_ASYNC',
    CARD_MANAGER_CREATE_CARD_ASYNC: 'CARD_MANAGER_CREATE_CARD_ASYNC',
    CARD_MANAGER_UPDATE_CARD_ASYNC: 'CARD_MANAGER_UPDATE_CARD_ASYNC',
    CARD_MANAGER_REMOVE_CARD_ASYNC: 'CARD_MANAGER_REMOVE_CARD_ASYNC',
});
